### ISSUE TITLE
TA Email addresses

### ISSUE THREAD

**Issue by Hoverbear** [fherwig/physmath248_pilot#1]
[The Week 01 notebook](https://github.com/fherwig/physmath248_pilot/blob/master/Week_01.ipynb) says email the TA's your github username however it does not tell you what those emails are!

**Comment by fherwig** [comment]
I know … we’ll get there! No worries. Thanks for the note.
F.

On Jan 6, 2016, at 9:09 AM, Andrew Hobden <notifications@github.com<mailto:notifications@github.com>> wrote:


The Week 01 notebook<https://github.com/fherwig/physmath248_pilot/blob/master/Week_01.ipynb> says email the TA's your github username however it does not tell you what those emails are!

—
Reply to this email directly or view it on GitHub<https://github.com/fherwig/physmath248_pilot/issues/1>.

--
Falk Herwig
Dept of Physics & Astronomy, U of Victoria
fherwig@uvic.ca<mailto:fherwig@uvic.ca>, tel: +1 (250) 721-7743

**Comment by critter1** [comment]
The email addresses are now available at <https://github.com/fherwig/physmath248_pilot/blob/master/README.md>.
Christian

**Comment by Hoverbear** [comment]
Thanks!
