### ISSUE TITLE
Link broken in week 2 notebook.

### ISSUE THREAD

**Issue by Hoverbear** [fherwig/physmath248_pilot#4]
The link http://astrowww.phys.uvic.ca/~fherwig/ftp/TEACHING/PHYS280/Phast_CP_V_03.pdf is broken in the week 2 notebook.

Attempting to use the following all failed:

* http://astro.phys.uvic.ca/~fherwig/ftp/TEACHING/PHYS280/Phast_CP_V_03.pdf
* http://www.phys.uvic.ca/~fherwig/ftp/TEACHING/PHYS280/Phast_CP_V_03.pdf
* http://astro.phys.uvic.ca/~fherwig/

**Comment by fherwig** [comment]
Thanks for noticing this. Fixed.
